debug: false
server-id: 1
secret-key: aaaa
pvp-protection-time: 60
spawn-kill-timeout: 60
hunger-protection-time: 60
newbie-stalker-threshold: 40
end-reset-period: 0
pvp-log-threshold: 5
nerf-endermen-drops: false
nerf-pigzombie-drops: false
animal-chunk-cap: 30
endpoint: http://standardsurvival.com/api/v1/
rts-address: http://rts.standardsurvival.com